name: harp
dependencies:
  - python=3.11.4 
  - pip=23.2.1
  - pip:
    - matplotlib==3.7.1
    - numpy==1.25.2
    - opencv_python==4.7.0.72
    - opencv_python_headless==4.8.1.78
    - pandas==2.0.1
    - Pillow==10.0.0
    - pytorch_lightning==1.9.5
    - scikit_learn==1.2.2
    - scipy==1.13.0
    - seaborn==0.13.2
    - scikit-image==0.20.0
    - tifffile==2023.4.12
    - torch==2.0.1
    - torchmetrics==0.10.3
    - torchvision==0.15.2
    - tqdm==4.65.0
    - zarr==2.14.2